name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Show help (no ffmpeg/keys needed)
        run: |
          python make_videos.py --help || true
      - name: Lint structure
        run: |
          test -d input_videos
          test -d music
          test -f make_videos.py
